# Generated by Django 3.2.9 on 2021-12-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=20)),
                ('grade', models.IntegerField()),
                ('courseNum', models.CharField(max_length=20)),
                ('classNum', models.IntegerField()),
                ('classTime', models.CharField(max_length=20)),
                ('classRoom', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
            ],
        ),
    ]
