# Generated by Django 3.2.9 on 2021-12-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classRoom',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseNum',
        ),
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='classNum',
            field=models.IntegerField(null=True),
        ),
    ]
