# Generated by Django 4.0 on 2021-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20211218_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
